INSERT INTO missed_projects ( 
   title, 
   track, 
   project_name, 
   source, 
   review_date, 
   miss_type, 
   signal, 
   reason, 
   trend, 
   exposed_problem, 
   extracted_lesson, 
   summary_conclusion, 
   short_lesson, 
   note, 
   is_deleted 
 ) VALUES 
 ( 
   '比特币牛市错过', 
   '加密货币', 
   '比特币', 
   'Twitter', 
   '2024-01-01', 
   '认知不足', 
   '机构资金持续流入，ETF获批', 
   '对加密货币监管环境过于悲观', 
   '价格从30000美元上涨到60000美元', 
   '对监管风险的过度担忧', 
   '关注机构资金动向，不要过度解读短期监管消息', 
   '错过比特币牛市是因为对监管环境的过度悲观', 
   '机构资金是市场的重要风向标', 
   '需要建立更系统化的加密货币分析框架', 
   0 
 );