import type { Express } from "express";
import priceRoutes from "./priceRoutes";
import masterDataRoutes from "./masterDataRoutes";
import positionRoutes from "./positionRoutes";
import followRoutes from "./followRoutes";
import planRoutes from "./planRoutes";
import watchlistRoutes from "./watchlistRoutes";
import eventRecordsRoutes from "./eventRecordsRoutes";
import opinionRecordsRoutes from "./opinionRecordsRoutes";
import missedProjectsRoutes from "./missedProjectsRoutes";
import tradeReviewsRoutes from "./tradeReviewsRoutes";
import treeHangingCasesRoutes from "./treeHangingCasesRoutes";
import marketReviewsRoutes from "./marketReviewsRoutes";
import ruleExperiencesRoutes from "./ruleExperiencesRoutes";
import originalPriceRecordsRoutes from "./originalPriceRecordsRoutes";
import annualPlansRoutes from "./annualPlansRoutes";
import annualPlanItemsRoutes from "./annualPlanItemsRoutes";
import annualPlanItemChangesRoutes from "./annualPlanItemChangesRoutes";
import endedPositionsRoutes from "./endedPositionsRoutes";
import sellRecordsRoutes from "./sellRecordsRoutes";
import dashboardRoutes from "./dashboardRoutes";
import monitorRulesRoutes from "./monitorRulesRoutes";
import abnormalMonitorRoutes from "./abnormalMonitorRoutes";
import volatilityAnalysisRoutes from "./volatilityAnalysisRoutes";
import elasticityAnalysisRoutes from "./elasticityAnalysisRoutes";
import riskControlRoutes from "./riskControlRoutes";
import footballLotteryRoutes from "./footballLotteryRoutes";
import rejectedOpportunitiesRoutes from "./rejectedOpportunitiesRoutes";
import speculationCycleRoutes from "./speculationCycleRoutes";
import productSupplyEventsRoutes from "./productSupplyEventsRoutes";

export const registerBusinessRoutes = (app: Express) => {
  app.use("/api", priceRoutes);
  app.use("/api", masterDataRoutes);
  app.use("/api", positionRoutes);
  app.use("/api", followRoutes);
  app.use("/api", planRoutes);
  app.use("/api", watchlistRoutes);
  app.use("/api", eventRecordsRoutes);
  app.use("/api", opinionRecordsRoutes);
  app.use("/api", missedProjectsRoutes);
  app.use("/api", tradeReviewsRoutes);
  app.use("/api", treeHangingCasesRoutes);
  app.use("/api", marketReviewsRoutes);
  app.use("/api", ruleExperiencesRoutes);
  app.use("/api", originalPriceRecordsRoutes);
  app.use("/api", annualPlansRoutes);
  app.use("/api", annualPlanItemsRoutes);
  app.use("/api", annualPlanItemChangesRoutes);
  app.use("/api", endedPositionsRoutes);
  app.use("/api", sellRecordsRoutes);
  app.use("/api/dashboard", dashboardRoutes);
  app.use("/api/monitor-rules", monitorRulesRoutes);
  app.use("/api/abnormal-monitor", abnormalMonitorRoutes);
  app.use("/api/volatility-analysis", volatilityAnalysisRoutes);
  app.use("/api/elasticity-analysis", elasticityAnalysisRoutes);
  app.use("/api/risk", riskControlRoutes);
  app.use("/api/football-lottery", footballLotteryRoutes);
  app.use("/api", rejectedOpportunitiesRoutes);
  app.use("/api", speculationCycleRoutes);
  app.use("/api", productSupplyEventsRoutes);
};
