import type { Express, Request, RequestHandler, Response } from "express";
import {
  isSupportedPasswordHash,
  readCookie,
  SESSION_COOKIE_NAME,
  verifySessionToken,
  type SessionAuthCredentials
} from "../services/sessionAuth";

export type DeploymentMode = "local" | "remote";
export type ServerAuthMode = "none" | "trusted_reverse_proxy" | "session";

export interface ServerSecurityConfig {
  nodeEnv: string;
  deploymentMode: DeploymentMode;
  host: string;
  port: number;
  publicBaseUrl: string | null;
  trustProxy: false | "loopback";
  authMode: ServerAuthMode;
  identityHeader: string | null;
  proxyAuthHeader: string | null;
  proxySharedSecret: string | null;
  sessionAuth: SessionAuthCredentials | null;
}

export class ServerSecurityConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ServerSecurityConfigError";
  }
}

const LOOPBACK_HOSTS = new Set(["localhost", "127.0.0.1", "::1"]);
const LOCAL_DEVELOPMENT_ORIGINS = [
  "http://localhost:5173",
  "http://127.0.0.1:5173",
  "http://[::1]:5173"
];

const normalizeHost = (value: string) => {
  const normalized = value.trim().replace(/^\[|\]$/g, "").toLowerCase();
  return normalized.startsWith("::ffff:") ? normalized.slice("::ffff:".length) : normalized;
};

export const isLoopbackHost = (value: string) => LOOPBACK_HOSTS.has(normalizeHost(value));

export const resolveAllowedCorsOrigins = (
  config: ServerSecurityConfig,
  configuredOrigins: string[]
) => new Set([
  ...(config.deploymentMode === "local" ? LOCAL_DEVELOPMENT_ORIGINS : []),
  ...configuredOrigins
]);

const parsePort = (value: string | undefined) => {
  const port = Number(value || 3001);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new ServerSecurityConfigError("PORT must be an integer between 1 and 65535");
  }
  return port;
};

const parseDeploymentMode = (value: string | undefined, isProduction: boolean): DeploymentMode => {
  const normalized = String(value || "").trim().toLowerCase();
  if (!normalized) {
    if (isProduction) {
      throw new ServerSecurityConfigError("Production requires an explicit DEPLOYMENT_MODE=local or remote");
    }
    return "local";
  }
  if (normalized !== "local" && normalized !== "remote") {
    throw new ServerSecurityConfigError("DEPLOYMENT_MODE must be local or remote");
  }
  return normalized;
};

const parseHttpsPublicBaseUrl = (value: string | undefined) => {
  const normalized = String(value || "").trim();
  if (!normalized) {
    throw new ServerSecurityConfigError("Remote deployment requires PUBLIC_BASE_URL");
  }
  try {
    const parsed = new URL(normalized);
    if (parsed.protocol !== "https:") {
      throw new ServerSecurityConfigError("Remote PUBLIC_BASE_URL must use HTTPS");
    }
    return parsed.toString().replace(/\/$/, "");
  } catch (error) {
    if (error instanceof ServerSecurityConfigError) throw error;
    throw new ServerSecurityConfigError("PUBLIC_BASE_URL must be a valid HTTPS URL");
  }
};

const parseIdentityHeader = (value: string | undefined) => {
  const normalized = String(value || "").trim().toLowerCase();
  if (!normalized || !/^[a-z0-9-]+$/.test(normalized)) {
    throw new ServerSecurityConfigError("Remote deployment requires a valid AUTH_IDENTITY_HEADER");
  }
  return normalized;
};

const parseProxyAuthHeader = (value: string | undefined) => {
  const normalized = String(value || "x-price-dashboard-proxy-secret").trim().toLowerCase();
  if (!normalized || !/^[a-z0-9-]+$/.test(normalized)) {
    throw new ServerSecurityConfigError("AUTH_PROXY_SECRET_HEADER must be a valid header name");
  }
  return normalized;
};

const parseProxySharedSecret = (value: string | undefined) => {
  const secret = String(value || "").trim();
  if (secret.length < 32) {
    throw new ServerSecurityConfigError(
      "trusted_reverse_proxy requires AUTH_PROXY_SHARED_SECRET with at least 32 characters"
    );
  }
  return secret;
};

const allowsUnauthenticatedLocal = (env: NodeJS.ProcessEnv) => {
  const value = String(env.ALLOW_UNAUTHENTICATED_LOCAL || "").trim().toLowerCase();
  return value === "1" || value === "true" || value === "yes";
};

const parseSessionAuthCredentials = (
  env: NodeJS.ProcessEnv,
  secureCookie: boolean
): SessionAuthCredentials => {
  const username = String(env.AUTH_USERNAME || "").trim();
  if (!username || username.length > 100 || /[\u0000-\u001f\u007f]/.test(username)) {
    throw new ServerSecurityConfigError(
      "Session authentication requires a valid AUTH_USERNAME"
    );
  }

  const passwordHash = String(env.AUTH_PASSWORD_HASH || "").trim();
  if (!isSupportedPasswordHash(passwordHash)) {
    throw new ServerSecurityConfigError(
      "Session authentication requires AUTH_PASSWORD_HASH generated by the project script"
    );
  }

  const sessionSecret = String(env.AUTH_SESSION_SECRET || "").trim();
  if (sessionSecret.length < 32) {
    throw new ServerSecurityConfigError(
      "Session authentication requires AUTH_SESSION_SECRET with at least 32 characters"
    );
  }

  const ttlHours = Number(env.AUTH_SESSION_TTL_HOURS || 12);
  if (!Number.isFinite(ttlHours) || ttlHours < 1 || ttlHours > 168) {
    throw new ServerSecurityConfigError(
      "AUTH_SESSION_TTL_HOURS must be between 1 and 168"
    );
  }

  return {
    username,
    passwordHash,
    sessionSecret,
    sessionTtlSeconds: Math.round(ttlHours * 60 * 60),
    secureCookie
  };
};

const assertRemoteCorsOriginsUseHttps = (value: string | undefined) => {
  const origins = String(value || "")
    .split(",")
    .map(origin => origin.trim())
    .filter(Boolean);
  if (origins.length === 0) {
    throw new ServerSecurityConfigError("Remote deployment requires explicit CORS_ORIGINS");
  }
  for (const origin of origins) {
    try {
      if (new URL(origin).protocol !== "https:") {
        throw new ServerSecurityConfigError("Remote CORS_ORIGINS must use HTTPS");
      }
    } catch (error) {
      if (error instanceof ServerSecurityConfigError) throw error;
      throw new ServerSecurityConfigError("Remote CORS_ORIGINS contains an invalid URL");
    }
  }
};

export const resolveServerSecurityConfig = (
  env: NodeJS.ProcessEnv = process.env
): ServerSecurityConfig => {
  const nodeEnv = String(env.NODE_ENV || "development").trim().toLowerCase();
  const isProduction = nodeEnv === "production";
  const deploymentMode = parseDeploymentMode(env.DEPLOYMENT_MODE, isProduction);
  const host = String(env.HOST || "127.0.0.1").trim();
  const port = parsePort(env.PORT);
  const requestedAuthMode = String(env.SERVER_AUTH_MODE || "").trim().toLowerCase();

  if (isProduction && !isLoopbackHost(host)) {
    throw new ServerSecurityConfigError(
      "Production API must bind to loopback and be exposed only through an authenticated HTTPS reverse proxy"
    );
  }

  if (deploymentMode === "local") {
    if (isProduction && !isLoopbackHost(host)) {
      throw new ServerSecurityConfigError("Local production mode requires a loopback HOST");
    }
    if (requestedAuthMode && !["none", "session"].includes(requestedAuthMode)) {
      throw new ServerSecurityConfigError(
        "Local mode SERVER_AUTH_MODE must be none or session"
      );
    }
    if (isProduction && requestedAuthMode !== "session" && !allowsUnauthenticatedLocal(env)) {
      throw new ServerSecurityConfigError(
        "Local production mode requires SERVER_AUTH_MODE=session (or explicit ALLOW_UNAUTHENTICATED_LOCAL=true)"
      );
    }
    if (requestedAuthMode === "session") {
      return {
        nodeEnv,
        deploymentMode,
        host,
        port,
        publicBaseUrl: null,
        trustProxy: false,
        authMode: "session",
        identityHeader: null,
        proxyAuthHeader: null,
        proxySharedSecret: null,
        sessionAuth: parseSessionAuthCredentials(env, false)
      };
    }
    return {
      nodeEnv,
      deploymentMode,
      host,
      port,
      publicBaseUrl: null,
      trustProxy: false,
      authMode: "none",
      identityHeader: null,
      proxyAuthHeader: null,
      proxySharedSecret: null,
      sessionAuth: null
    };
  }

  if (!isLoopbackHost(host)) {
    throw new ServerSecurityConfigError("Remote mode still requires a loopback HOST behind the reverse proxy");
  }
  if (String(env.TRUST_PROXY || "").trim().toLowerCase() !== "loopback") {
    throw new ServerSecurityConfigError("Remote mode requires TRUST_PROXY=loopback");
  }
  if (!["trusted_reverse_proxy", "session"].includes(requestedAuthMode)) {
    throw new ServerSecurityConfigError(
      "Remote mode requires SERVER_AUTH_MODE=trusted_reverse_proxy or session"
    );
  }

  assertRemoteCorsOriginsUseHttps(env.CORS_ORIGINS);
  const authMode = requestedAuthMode as Exclude<ServerAuthMode, "none">;
  const useProxyAuth = authMode === "trusted_reverse_proxy";
  return {
    nodeEnv,
    deploymentMode,
    host,
    port,
    publicBaseUrl: parseHttpsPublicBaseUrl(env.PUBLIC_BASE_URL),
    trustProxy: "loopback",
    authMode,
    identityHeader: useProxyAuth
      ? parseIdentityHeader(env.AUTH_IDENTITY_HEADER)
      : null,
    proxyAuthHeader: useProxyAuth
      ? parseProxyAuthHeader(env.AUTH_PROXY_SECRET_HEADER)
      : null,
    proxySharedSecret: useProxyAuth
      ? parseProxySharedSecret(env.AUTH_PROXY_SHARED_SECRET)
      : null,
    sessionAuth: authMode === "session"
      ? parseSessionAuthCredentials(env, true)
      : null
  };
};

const isDirectLoopbackHealthRequest = (req: Parameters<RequestHandler>[0]) => {
  const remoteAddress = normalizeHost(String(req.socket.remoteAddress || ""));
  return req.path === "/health"
    && isLoopbackHost(remoteAddress)
    && !req.headers["x-forwarded-for"];
};

export const applyServerSecurity = (app: Express, config: ServerSecurityConfig) => {
  if (config.trustProxy) app.set("trust proxy", config.trustProxy);
};

export const enforceRemoteRequestBoundary = (
  req: Request,
  res: Response,
  config: ServerSecurityConfig
) => {
  if (config.deploymentMode !== "remote") return true;
  if (!req.secure) {
    res.status(426).json({
      status: "error",
      code: "https_required",
      message: "HTTPS is required"
    });
    return false;
  }
  if (!req.headers["x-forwarded-for"]) {
    res.status(403).json({
      status: "error",
      code: "reverse_proxy_required",
      message: "Authenticated reverse proxy required"
    });
    return false;
  }
  return true;
};

export const createRemoteAuthenticationMiddleware = (
  config: ServerSecurityConfig
): RequestHandler => {
  if (config.authMode === "none") {
    return (_req, _res, next) => next();
  }

  return (req, res, next) => {
    if (isDirectLoopbackHealthRequest(req)) {
      next();
      return;
    }

    if (!enforceRemoteRequestBoundary(req, res, config)) return;

    if (config.authMode === "trusted_reverse_proxy") {
      const proxySecret = String(req.get(config.proxyAuthHeader as string) || "").trim();
      if (!proxySecret || proxySecret !== config.proxySharedSecret) {
        res.status(401).json({
          status: "error",
          code: "authentication_required",
          message: "Authentication required"
        });
        return;
      }
      const identity = String(req.get(config.identityHeader as string) || "").trim();
      if (!identity) {
        res.status(401).json({
          status: "error",
          code: "authentication_required",
          message: "Authentication required"
        });
        return;
      }
      res.locals.authenticatedIdentity = identity;
      next();
      return;
    }

    const credentials = config.sessionAuth as SessionAuthCredentials;
    const token = readCookie(req.headers.cookie, SESSION_COOKIE_NAME);
    const session = token ? verifySessionToken(token, credentials) : null;
    if (!session) {
      res.status(401).json({
        status: "error",
        code: "authentication_required",
        message: "Authentication required"
      });
      return;
    }

    res.locals.authenticatedIdentity = session.sub;
    next();
  };
};
